name: API Production
on:
  push:
    branches:
      - development
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy via SSH
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.AWS_HOSTNAME }}
          USER_NAME: 'ubuntu'
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd user-todogochi
            git pull origin development
            npm install &&
            npm run build &&
            pm2 restart ecosystem.config.js
          '
